import { DataItem } from "../goldenVisa/data";

export const data: DataItem[] = [
  {
    id: "1",
    title: "New Entry Permits",
    services: [
      {
        heading: "Spouse Residence Visa",
        subHeading: "Read more about required documents, details & apply now",
        slug: "spouse_residence_visa",
        price: "Inside: 1188.90 AED <br/> Outside: 538.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Marriage certificate [Attested by the UAE MOFA & Translated into Arabic]",
          "Trade Licence, MOA & Establishment card [If the Sponsor is Investor/Partner - AED 3000 Security Deposit]",
          "Labour Contract with Ministry Stamp [If the Sponsor is working in the Private Sector - Salary should be AED 4,000 or above]",
          "Arabic Salary Certificate issued by Free zone Authority [If Sponsor Working in Free Zone Sector - Salary should be AED 4,000 or above]",
          "Arabic Salary Certificate issued by Employer [If Sponsor Working in Govt./Semi Govt. Sector - Salary should be AED 4,000 or above]",
        ],
        redpoints: [
          "** AED 253.15 to be paid, If the Sponsor doesn’t have an active Sponsorship file",
          "** Applicant’s National ID required for Pakistan, Afghanistan, Iran & Iraq Nationality",
        ],
      },
      {
        heading: "Son / Daughter Residence Visa",
        subHeading: "Read more about required documents, details & apply now",
        slug: "son_daughter_residence_visa",
        price: "Inside: 1188.90 AED <br/> Outside: 538.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Birth certificate [Attested by the UAE MOFA & Translated into Arabic]",
          "Trade Licence, MOA & Establishment card [If the Sponsor is Investor/Partner - AED 3000 Security Deposit]",
          "Labour Contract with Ministry Stamp [If the Sponsor is working in the Private Sector - Salary should be AED 4,000 or above]",
          "Arabic Salary Certificate issued by Free zone Authority [If Sponsor Working in Free Zone Sector - Salary should be AED 4,000 or above]",
          "Arabic Salary Certificate issued by Employer [If Sponsor Working in Govt./Semi Govt. Sector - Salary should be AED 4,000 or above]",
        ],
        redpoints: [
          "** AED 253.15 to be paid, If the Sponsor doesn’t have an active Sponsorship file",
          "** Mother’s visa copy is to be provided if requested by the GDRFA",
          "** An Unmarried letter from the sponsor is required for a daughter above the age of 18",
          "** A Study letter of the applicant is required for a son above the age of 18",
          "** NOC from Father Certified by Dubai Court [If Mother is the Sponsor] OR Death Certificate MOFA Attested [If father Deceased]",
          "** An attested divorce certificate & custody documents of the child (In case of divorce)",
          "** Applicant’s National ID required for Pakistan, Afghanistan, Iran & Iraq Nationality",
        ],
      },
      {
        heading: "Parent’s Residence Visa",
        subHeading: "Read more about required documents, details & apply now",
        slug: "parents_residence_visa",
        price: "Inside: 1188.90 AED <br/> Outside: 538.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Attested Birth Certificate of Sponsor [Attested by the UAE MOFA & Translated into Arabic]",
          "Attested Birth Certificate of Spouse [Attested by the UAE MOFA & Translated into Arabic] - For Parents in Law",
          "Attested Marriage Certificate of Sponsor [Attested by the UAE MOFA & Translated into Arabic] - For Parents in Law",
          "Consanguinity letter / Sponsorship letter from sponsor’s consulate or embassy in UAE (UAE MOFA Attested and translated into Arabic)",
          "Tenancy Contract /Ejari/Title Deed [02 Bedroom & Hall]",
          "Sponsor’s Bank Statement for the Last 03 Months",
          "Trade Licence, MOA & Establishment card [If the Sponsor is an Investor/Partner]",
          "Labour Contract with Ministry Stamp [If the Sponsor is working in the Private Sector - Salary should be AED 10,000 or above]",
          "Arabic Salary Certificate issued by Free zone Authority [If Sponsor Working in Free Zone Sector - Salary should be AED 10,000 or above]",
          "Arabic Salary Certificate issued by Employer [If Sponsor Working in Govt./Semi Govt. Sector - Salary should be AED 10,000 or above]",
        ],
        redpoints: [
          "** There will be Security Deposit AED 5000 for each parent",
          "** AED 253.15 to be paid, If the Sponsor doesn’t have an active Sponsorship file",
          "** Applicant’s National ID required for Pakistan, Afghanistan, Iran & Iraq Nationality",
        ],
      },
      {
        heading: "Investor/Partner Visa",
        subHeading: "Read more about required documents, details & apply now",
        slug: "investor_partner_visa",
        price: "Inside: 1225.90 AED <br/> Outside: 576.90 AED",
        reqDocs: [
          "Original Emirates ID of the sponsor/owner or Current visa copy of the owner",
          "Trade license copy + Establishment card + Memorandum from DED or the Court (if the owner has an LLC company. It is also not mandatory if the owner does not have a memorandum)",
          "Passport copy + 1 Digital photo with white background + current visa copy",
        ],
        redpoints: [
          "** Applicant’s National ID Required for Pakistan, Afghanistan, Iran & Iraq Nationality",
        ],
      },
      {
        heading: "Employment Visa",
        subHeading: "Read more about required documents, details & apply now",
        slug: "employment_visa",
        price: "Inside: 1225.90 AED <br/> Outside: 576.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Trade Licence, MOA & Establishment Card Copy",
          "Entry Permit Approval from MOHRE",
        ],
        redpoints: [
          "** Applicant’s National ID Required for Pakistan, Afghanistan & Iraq Nationality",
        ],
      },
      {
        heading: "Virtual Work Visa [Remote Work Visa]",
        subHeading: "Read more about required documents, details & apply now",
        slug: "virtual_work_visa",
        price: "Inside: 1225.90 AED",
        reqDocs: [
          "Salary certificate issued from the company of the applicant mentioning the applicant's name, the position being held, passport number, and current monthly gross salary. (This should be in the company letter headed paper + company stamp and signature of the signatory to Authority)",
          "6-month bank statement stating the monthly salary as not being less than 3500USD (10,000AED). If the applicant is a resident inside the UAE, the bank statement can be obtained from the applicant's bank inside the UAE and if the applicant is a resident outside the UAE the bank statement can be obtained from the applicant's bank outside the UAE",
          "Valid Health insurance for a full year from the current month of application of the virtual/remote work visa",
          "A letter of appointment to work remotely, issued from the sponsor to the sponsored person, indicating the monthly salary is not less than $3,500 and the profession + Applicants Employment contract",
          "Applicant passport copy, 1 clear digitally taken photo on a white background",
          "If the applicant is inside the UAE with a visit visa, then a visit visa copy will be required. And if the applicant has a residence visa, then a copy of the applicant's residence visa + EID will be required",
        ],
        redpoints: [],
      },
      {
        heading: "Re-Entry Permit",
        subHeading: "Read more about required documents, details & apply now",
        slug: "re_entry_permit",
        price: "Outside: 488.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy & Residence Visa Copy",
          "Applicant’s Emirates ID Copy & Residence Visa Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Letter with Valid Reason for staying outside more than 06 Months",
        ],
        redpoints: [
          "** If more than 06 months, then there will be an additional 100AED per month after the 06th Month",
        ],
      },
    ],
  },

  {
    id: "2",
    title: "Long Term Visa",
    services: [
      {
        heading: "Long Term Visit Visa Inside the Country",
        subHeading: "Read more about required documents, details & apply now",
        slug: "long_term_visit_visa_inside_the_country",
        price:
          "  Inside 1225.90 AED                <br/>                            Outside: 576.90 AED",
        reqDocs: [
          "Original sponsor's Emirates ID",
          "Immigration Establishment Card Copy + Trade License",
          "Current Visa",
          "Sponsored Passport + 1 latest photo 2x2 size (Studio type)",
          "MOHRE approval permit",
        ],
        redpoints: [
          "** National ID is required for (Pakistan - Afghanistan - Iraq) Nationalities ",
        ],
      },
    ],
  },

  {
    id: "3",
    title: "Visa Extension",
    services: [
      {
        heading: "Visit Visa Extend",
        subHeading: "Read more about required documents, details & apply now",
        slug: "visit_visa_extend",
        price: "   995.90 AED",
        reqDocs: [
          "Applicant Passport + Entry Permit copy",
          "Sponsor Original ID",
        ],
        redpoints: [""],
      },
      {
        heading: "Gulf Residents Visit Visa Extend",
        subHeading: "Read more about required documents, details & apply now",
        slug: "gulf_residents_visit_visa_extend",
        price: "   995.90 AED",
        reqDocs: [
          "Applicant GCC National ID",
          "Applicant Passport and Entry Permit",
        ],
        redpoints: [""],
      },
      {
        heading: "On Arrival Visa Extension",
        subHeading: "Read more about required documents, details & apply now",
        slug: "on_arrival_visa_extension",
        price: "   995.90 AED",
        reqDocs: [":Applicant Passport copy"],
        redpoints: [""],
      },
    ],
  },
  {
    id: "4",
    title: "New Born Residence Visa",
    services: [
      {
        heading: "New Born Residence Visa",
        subHeading: "Read more about required documents, details & apply now",
        slug: "new_born_residence_visa",
        price: "Inside: 609.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Mother Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Arabic Birth certificate",
          "Trade Licence, MOA & Establishment card [If Sponsor Investor/Partner - AED 3000 Security Deposit]",
          "Labour Contract with Ministry Stamp [If Sponsor working in Private Sector - Minimum Salary AED 4,000]",
          "Salary Certificate Issued by Free zone Authority [If Sponsor Working in Free Zone Sector - Minimum Salary AED 4,000]",
          "Salary Certificate Issued by Employer [If Sponsor Working in Govt./Semi Govt. Sector - Minimum Salary AED 4,000]",
        ],
        redpoints: [
          "** AED 253.15 to be paid, If the Sponsor doesn’t have an active Sponsorship file",
          "** NOC from Father Certified by Dubai Court [If Mother is the Sponsor] OR Death Certificate MOFA Attested [If father Deceased], An attested divorce certificate & custody documents of the child (In case of divorce)",
          "** Applicant National ID Required for Pakistan, Afghanistan, Iran & Iraq Nationality",
        ],
      },
    ],
  },

  {
    id: "5",
    title: "Residence Visa Renewal",
    services: [
      {
        heading: "Spouse & Children Visa Renewal",
        subHeading: "Read more about required documents, details & apply now",
        slug: "spouse_children_visa_renewal",
        price: "Inside: 609.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Emirates ID copy & Residence Visa Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Emirates ID Application Form of the Applicant",
          "Medical FIT Certificate of the Applicant [For applicants aged 18 & above]",
          "Trade Licence, MOA & Establishment card [If Sponsor Investor/Partner]",
          "Labour Contract with Ministry Stamp [If the Sponsor is working in the Private Sector - Salary should be AED 4,000 or above]",
          "Arabic Salary Certificate issued by Free zone Authority [If Sponsor Working in Free Zone Sector - Salary should be AED 4,000 or above]",
          "Arabic Salary Certificate issued by Employer [If Sponsor Working in Govt./Semi Govt. Sector - Salary should be AED 4,000 or above]",
        ],
        redpoints: [
          "** An Unmarried letter from the sponsor is required for a daughter above the age of 18",
          "** A Study letter of the applicant is required for a son above the age of 18",
          "** The Applicant's should be in the country",
        ],
      },
      {
        heading: "Parents Visa Renewal (01 Year)",
        subHeading: "Read more about required documents, details & apply now",
        slug: "parents_visa_renewal",
        price: "Inside: 509.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Emirates ID copy & Residence Visa Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Emirates ID Application Form of the applicant",
          "Medical FIT Certificate of the applicant",
          "Tenancy Contract /Ejari/Title Deed [02 Bedroom & Hall]",
          "Sponsor’s Bank Statement for Last 03 Months",
          "Trade Licence, MOA & Establishment card [If Sponsor Investor/Partner]",
          "Labour Contract with Ministry Stamp [If the Sponsor is working in the Private Sector - Salary should be AED 10,000 or above]",
          "Arabic Salary Certificate issued by Free zone Authority [If Sponsor Working in Free Zone Sector - Salary should be AED 10,000 or above]",
          "Arabic Salary Certificate issued by Employer [If Sponsor Working in Govt./Semi Govt. Sector - Salary should be AED 10,000 or above]",
        ],
        redpoints: ["** The Applicant's should be in the country"],
      },
      {
        heading: "Employment Visa Renewal",
        subHeading: "Read more about required documents, details & apply now",
        slug: "employment_visa_renewal",
        price: "Inside: 646.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Emirates ID copy & Residence Visa Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Trade Licence, MOA & Establishment Card Copy",
          "Emirates ID Application Form of the Applicant",
          "Medical FIT Certificate of the Applicant",
        ],
        redpoints: ["** The Applicant's should be in the country"],
      },
      {
        heading: "Partner/Investor Visa Renewal",
        subHeading: "Read more about required documents, details & apply now",
        slug: "partner_investor_visa_renewal",
        price: "Inside: 646.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Emirates ID copy & Residence Visa Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Memorandum of association from DED or the Court /agreement with Local Agent",
          "Trade license & Establishment card copy",
          "Emirates ID Application Form of the Applicant",
          "Medical FIT Certificate of the Applicant",
          "Company bank statement for the last 03/06 months (If requested by the GDRFA)",
        ],
        redpoints: ["** The Applicant's should be in the country"],
      },
      {
        heading: "Virtual Visa Renewal",
        subHeading: "Read more about required documents, details & apply now",
        slug: "virtual_visa_renewal",
        price: "Inside: 546.90 AED",
        reqDocs: [
          "Applicant’s Original Emirates ID",
          "Applicant’s Emirates ID Copy, Residence Visa copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Salary certificate issued from the company of the applicant",
          "Valid Health insurance for a full year from the current month of application of the virtual/remote work visa",
          "A letter of appointment to work remotely, issued from the sponsor to the sponsored person",
          "Emirates ID Application Form of the Applicant",
          "Medical FIT Certificate of the Applicant",
        ],
        redpoints: ["** The Applicant's should be in the country"],
      },
    ],
  },
  {
    id: "6",
    title: "Residence Visa Stamping",
    services: [
      {
        heading: "Spouse & Children Visa Stamping",
        subHeading: "Read more about required documents, details & apply now",
        slug: "spouse_children_visa_stamping",
        price: "Inside: 609.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Applicant’s Approved Entry permit copy",
          "Emirates ID Application Form of the Applicant",
          "Medical FIT Certificate of the Applicant [For applicants aged 18 & above]",
          "Trade Licence, MOA & Establishment card [If Sponsor Investor/Partner]",
          "Labour Contract with Ministry Stamp [If the Sponsor is working in the Private Sector - Salary should be AED 4,000 or above]",
          "Arabic Salary Certificate issued by Free zone Authority [If Sponsor Working in Free Zone Sector - Salary should be AED 4,000 or above]",
          "Arabic Salary Certificate issued by Employer [If Sponsor Working in Govt./Semi Govt. Sector - Salary should be AED 4,000 or above]",
        ],
        redpoints: ["** The Applicant's should be in the country"],
      },
      {
        heading: "Parents Visa Stamping (01 Year)",
        subHeading: "Read more about required documents, details & apply now",
        slug: "parents_visa_stamping",
        price: "Inside: 509.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Applicant’s Approved Entry permit copy",
          "Emirates ID Application Form of Applicant",
          "Medical FIT Certificate of Applicant",
          "Tenancy Contract /Ejari/Title Deed [02 Bedroom & Hall]",
          "Sponsor’s Bank Statement for Last 03 Months",
          "Trade Licence, MOA & Establishment card [If Sponsor Investor/Partner]",
          "Labour Contract with Ministry Stamp [If the Sponsor is working in the Private Sector - Salary should be AED 10,000 or above]",
          "Arabic Salary Certificate issued by Free zone Authority [If Sponsor Working in Free Zone Sector - Salary should be AED 10,000 or above]",
          "Arabic Salary Certificate issued by Employer [If Sponsor Working in Govt./Semi Govt. Sector - Salary should be AED 10,000 or above]",
        ],
        redpoints: ["** The Applicant's should be in the country"],
      },
      {
        heading: "Employment Visa Stamping",
        subHeading: "Read more about required documents, details & apply now",
        slug: "employment_visa_stamping",
        price: "Inside: 646.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Applicant’s Approved Entry permit copy",
          "Trade Licence, MOA & Establishment Card Copy",
          "Emirates ID Application Form of the Applicant",
          "Medical FIT Certificate of the Applicant",
        ],
        redpoints: ["** The Applicant's should be in the country"],
      },
      {
        heading: "Partner/Investor Visa Stamping",
        subHeading: "Read more about required documents, details & apply now",
        slug: "partner_investor_visa_stamping",
        price: "Inside: 646.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s one Digital Photo [From Studio]",
          "Memorandum of association from DED or the Court /agreement with Local Agent",
          "Trade license & Establishment card copy",
          "Applicant’s Approved Entry permit copy",
          "Emirates ID Application Form of the Applicant",
          "Medical FIT Certificate of the Applicant",
        ],
        redpoints: ["** The Applicant's should be in the country"],
      },
      {
        heading: "Virtual Visa Stamping (01 Year)",
        subHeading: "Read more about required documents, details & apply now",
        slug: "virtual_visa_stamping",
        price: "Inside: 546.90 AED",
        reqDocs: [
          "Applicant’s Approved Entry Permit Copy & Passport Copy",
          "Applicant’s one Digital Photo [From Studio]",
          "Salary certificate issued from the company of the applicant",
          "Valid Health insurance for a full year from the current month of application of the virtual/remote work visa",
          "A letter of appointment to work remotely, issued from the sponsor to the sponsored person",
          "Applicant’s Approved Entry permit copy",
          "Emirates ID Application Form of the Applicant",
          "Medical FIT Certificate of the Applicant",
        ],
        redpoints: ["** The Applicant's should be in the country"],
      },
    ],
  },
  {
    id: "7",
    title: "Cancellation",
    services: [
      {
        heading: "Family Residence Visa Cancellation",
        subHeading: "Read more about required documents, details & apply now",
        slug: "family_residence_visa_cancellation",
        price: "Inside: 288.90 AED <br/> Outside: 388.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Applicant’s residence Visa copy",
          "Applicant’s Passport Copy",
        ],
        redpoints: [
          "** Applicant Outside Less than 06 months - Sponsor Should visit Immigration with applicant Passport upon request from GDRFA-D",
        ],
      },
      {
        heading: "Employment Visa Cancellation",
        subHeading: "Read more about required documents, details & apply now",
        slug: "employment_visa_cancellation",
        price: "Inside: 325.90 AED <br/> Outside: 425.90 AED",
        reqDocs: [
          "Sponsor’s “OR” Applicant’s Original Emirates ID",
          "Applicant’s residence Visa copy",
          "Applicant’s Passport Copy",
        ],
        redpoints: [
          "** Labour Card should be cancelled before applying for the Visa cancellation",
        ],
      },
      {
        heading: "Partner / Investor Visa Cancellation",
        subHeading: "Read more about required documents, details & apply now",
        slug: "partner_investor_visa_cancellation",
        price: "Inside: 325.90 AED <br/> Outside: 425.90 AED",
        reqDocs: [
          "Emirates ID of one of the partners or sponsors, which should be the same as on the Establishment card.",
          "Applicant’s Emirates ID copy, Residence Visa Copy & Passport copy",
          "NOC for the cancellation (company letterhead paper and stamp) which should capture the company share division as well who will retain shares in the company",
        ],
        redpoints: [],
      },
      {
        heading: "Virtual Work Visa Cancellation",
        subHeading: "Read more about required documents, details & apply now",
        slug: "virtual_work_visa_cancellation",
        price: "Inside: 325.90 AED <br/> Outside: 425.90 AED",
        reqDocs: [
          "Applicant’s Original Emirates ID",
          "Applicant’s Passport copy & Emirates ID copy",
        ],
        redpoints: [],
      },
      {
        heading: "Cancellation - Entry Permit (After Entry) – Company",
        subHeading: "Read more about required documents, details & apply now",
        slug: "entry_permit_cancellation_company",
        price: "Inside: 288.90 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Applicant’s Passport copy",
          "Applicant’s Entry permit Copy",
        ],
        redpoints: [],
      },
      {
        heading: "Cancellation - Entry Permit (After Entry) – Company",
        subHeading: "Read more about required documents, details & apply now",
        slug: "entry_permit_cancellation_company_2",
        price: "Inside: 325.90 AED",
        reqDocs: ["Applicant’s Entry Permit", "Applicant Passport"],
        redpoints: [
          "** Labour Card should be cancelled before applying for the Visa cancellation",
        ],
      },
    ],
  },
  {
    id: "8",
    title: "Data Modification",
    services: [
      {
        heading: "Data Modification - Family",
        subHeading: "Read more about required documents, details & apply now",
        slug: "data_modification_family",
        price: "AED 409.90",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Emirates ID copy, Residence Visa Copy & Old Passport Copy",
          "Applicant Passport Copy [Old and New]",
          "Applicant’s one Digital Photo [From Studio]",
        ],
        redpoints: ["** The Applicant should be in the country"],
      },
      {
        heading: "Data Modification - Company",
        subHeading: "Read more about required documents, details & apply now",
        slug: "data_modification_company",
        price: "AED 447.90",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Emirates ID copy, Residence Visa Copy & Old Passport Copy",
          "Applicant Labour Card",
          "Applicant New Passport Copy",
          "Applicant’s one Digital Photo [From Studio]",
        ],
        redpoints: ["** The Applicant should be in the country"],
      },
    ],
  },

  {
    id: "9",
    title: "Travel Report",
    services: [
      {
        heading: "Travel Report - Family",
        subHeading: "Read more about required documents, details & apply now",
        slug: "travel_report_family",
        price: "  338.90 AED",
        reqDocs: ["Applicant Original ID", "Applicant Passport + Visa copy"],
        redpoints: [
          "** Important note: All Documents must scan clear and in colored copy",
        ],
      },
      {
        heading: "Travel Report - Company",
        subHeading: "Read more about required documents, details & apply now",
        slug: "travel_report_company",
        price: " 374.90 AED",
        reqDocs: [
          "Original PRO ID card / sponsor ID + applicant (passport + visa)",
          "Or applicant ID copy",
          "Establishment card",
        ],
        redpoints: [
          "** Important note: All Documents must scan clear and in colored copy",
        ],
      },
    ],
  },
  {
    id: "10",
    title: "Establishment Card",
    services: [
      {
        heading: "New Establishment Card with Online",
        subHeading: "Read more about required documents, details & apply now",
        slug: "new_establishment_card_with_online",
        price: " 2880.90 AED",
        reqDocs: [
          "Original sponsors Emirates ID",
          "Copy of Trade License & Partner list Page",
          "Passport copy of all partners",
        ],
        redpoints: [],
      },
      {
        heading: "New Establishment Card without Online",
        subHeading: "Read more about required documents, details & apply now",
        slug: "new_establishment_card_without_online",
        price: "  576.90 AED",
        reqDocs: [
          "Copy of Establishment Card",
          "Original sponsors Emirates ID",
          "Copy of Trade License & Partner list Page",
          "Passport copy of all partners",
        ],
        redpoints: [],
      },
      {
        heading: "Renewal of - Establishment Card with Online",
        subHeading: "Read more about required documents, details & apply now",
        slug: "renewal_of_establishment_card_with_online",
        price: " 1825.90 AED",
        reqDocs: [
          "Copy of Establishment Card",
          "Original sponsors Emirates ID",
          "Copy of Trade License & Partner list Page",
          "Passport copy of all partners",
        ],
        redpoints: [],
      },
      {
        heading: "Renewal of - Establishment Card without Online",
        subHeading: "Read more about required documents, details & apply now",
        slug: "renewal_of_establishment_card_without_online",
        price: " 676.90 AED ",
        reqDocs: [
          "Original sponsors Emirates ID",
          "Copy of Trade License & Partner list Page",
          "Passport copy of all partners",
        ],
        redpoints: [],
      },
    ],
  },

  {
    id: "12",
    title: "Change Status",
    services: [
      {
        heading: "Change Status - Family",
        subHeading: "Read more about required documents, details & apply now",
        slug: "change_status_family",
        price: " 738.90 AED",
        reqDocs: [
          "Sponsor’s Emirates ID copy",
          "Applicant’s Entry Permit Copy",
          "Applicant’s Passport copy",
        ],
        redpoints: [],
      },
      {
        heading: "Change Status - Company",
        subHeading: "Read more about required documents, details & apply now",
        slug: "change_status_company",
        price: "  775.90 AED",
        reqDocs: [
          "Sponsor’s Emirates ID copy",
          "Applicant’s Entry Permit Copy",
          "Applicant’s Passport copy",
        ],
        redpoints: [],
      },
      {
        heading: "Change Status - Sponsored Visit Visa",
        subHeading: "Read more about required documents, details & apply now",
        slug: "change_status_sponsored_visit_visa",
        price: " 718.90 AED",
        reqDocs: [
          "Sponsor’s Emirates ID copy",
          "Applicant’s Entry Permit Copy",
          "Applicant’s Passport copy",
        ],
        redpoints: [],
      },
    ],
  },

  {
    id: "13",
    title: "Security Deposit",
    services: [
      {
        heading: "Security Deposit",
        subHeading: "Read more about required documents, details & apply now",
        slug: "security_deposit",
        price: "Cost Depends <br/> on Application",
        reqDocs: [
          "Entry Permit Application",
          "Sponsor ID copy",
          "Applicant Passport",
        ],
        redpoints: [],
      },
    ],
  },
  {
    id: "14",
    title: "Holding Visa",
    services: [
      {
        heading: "Holding Visa",
        subHeading: "Read more about required documents, details & apply now",
        slug: "holding_visa",
        price: "398.90 AED",
        reqDocs: [
          "Sponsor Original Emirates ID",
          "New Offer letter",
          "Applicant Passport and Visa copy",
        ],
        redpoints: [
          "** Only Possible change Job within Dubai ",
          "** WARRANTY DEPOSIT – AED 5000 ",
          "** Additional AED 100 for Each Dependents",
        ],
      },
    ],
  },
  {
    id: "15",
    title: "Sponsored Visit Visa",
    services: [
      {
        heading: "Sponsored Visit Visa - 30 Days",
        subHeading: "Read more about required documents, details & apply now",
        slug: "sponsored_visit_visa_30_days",
        price: "Inside: 1250 AED <br/> Outside: 600 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Birth certificate [Attested by the UAE MOFA & Translated into Arabic] – For Children",
          "Marriage certificate [Attested by the UAE MOFA & Translated into Arabic] – For Spouse",
          "Sponsor Birth certificate [Attested by the UAE MOFA & Translated into Arabic] – For Parents",
          "Trade Licence, MOA & Establishment card [If Sponsor Investor/Partner]",
          "Labour Contract with Ministry Stamp [If Sponsor working in Private Sector - Minimum Salary AED 4,000]",
          "Salary Certificate Issued by Free zone Authority [If Sponsor Working in Free Zone Sector - Minimum Salary AED 4,000]",
          "Salary Certificate Issued by Employer [If Sponsor Working in Govt./Semi Govt. Sector - Minimum Salary AED 4,000]",
        ],
        redpoints: [
          "** AED 253.15 to be paid, If the Sponsor doesn’t have an active Sponsorship file",
          "** There will be Security Deposit AED 1000 for each Applicant (Refundable)",
          "** NOC from Father Certified by Dubai Court [If Mother is the Sponsor] OR Death Certificate MOFA Attested [If father Deceased]",
          "** Applicant National ID Required for Pakistan, Afghanistan, Iran & Iraq Nationality",
        ],
      },
      {
        heading: "Sponsored Visit Visa - 90 Days",
        subHeading: "Read more about required documents, details & apply now",
        slug: "sponsored_visit_visa_90_days",
        price: "Inside: 1520 AED <br/> Outside: 850 AED",
        reqDocs: [
          "Sponsor’s Original Emirates ID",
          "Sponsor’s Emirates ID Copy, Residence Visa Copy & Passport Copy",
          "Applicant’s Passport Copy [The passport should be valid for at least 6 months]",
          "Applicant’s one Digital Photo [From Studio]",
          "Birth certificate [Attested by the UAE MOFA & Translated into Arabic] – For Children",
          "Marriage certificate [Attested by the UAE MOFA & Translated into Arabic] – For Spouse",
          "Sponsor Birth certificate [Attested by the UAE MOFA & Translated into Arabic] – For Parents",
          "Trade Licence, MOA & Establishment card [If Sponsor Investor/Partner]",
          "Labour Contract with Ministry Stamp [If Sponsor working in Private Sector - Minimum Salary AED 4,000]",
          "Salary Certificate Issued by Free zone Authority [If Sponsor Working in Free Zone Sector - Minimum Salary AED 4,000]",
          "Salary Certificate Issued by Employer [If Sponsor Working in Govt./Semi Govt. Sector - Minimum Salary AED 4,000]",
        ],
        redpoints: [
          "** AED 253.15 to be paid, If the Sponsor doesn’t have an active Sponsorship file",
          "** There will be Security Deposit AED 1000 for each Applicant (Refundable)",
          "** NOC from Father Certified by Dubai Court [If Mother is the Sponsor] OR Death Certificate MOFA Attested [If father Deceased]",
          "** Applicant National ID Required for Pakistan, Afghanistan, Iran & Iraq Nationality",
        ],
      },
    ],
  },
];
